server:
  port: 8888

spring:
  application:
    name: own-config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Blucezhang/center-config.git
          search-paths: application-*,own-*
spring:
  profiles: dev
  security:
      user:
        password: ${CONFIG_SERVICE_PASSWORD}
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone:  http://own:123456@localhost:8002/eureka